//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9032.0.
// 
namespace DarwinClient.Schema.TimetableReference {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.thalesgroup.com/rtti/XmlRefData/v4")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.thalesgroup.com/rtti/XmlRefData/v4", IsNullable=false)]
    public partial class PportTimetableRef {
        
        private LocationRef[] locationRefField;
        
        private TocRef[] tocRefField;
        
        private Reason[] lateRunningReasonsField;
        
        private Reason[] cancellationReasonsField;
        
        private Via[] viaField;
        
        private CISSource[] cISSourceField;
        
        private CategoryData[] loadingCategoriesField;
        
        private string timetableIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LocationRef")]
        public LocationRef[] LocationRef {
            get {
                return this.locationRefField;
            }
            set {
                this.locationRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TocRef")]
        public TocRef[] TocRef {
            get {
                return this.tocRefField;
            }
            set {
                this.tocRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Reason", IsNullable=false)]
        public Reason[] LateRunningReasons {
            get {
                return this.lateRunningReasonsField;
            }
            set {
                this.lateRunningReasonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Reason", IsNullable=false)]
        public Reason[] CancellationReasons {
            get {
                return this.cancellationReasonsField;
            }
            set {
                this.cancellationReasonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Via")]
        public Via[] Via {
            get {
                return this.viaField;
            }
            set {
                this.viaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CISSource")]
        public CISSource[] CISSource {
            get {
                return this.cISSourceField;
            }
            set {
                this.cISSourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("category", IsNullable=false)]
        public CategoryData[] LoadingCategories {
            get {
                return this.loadingCategoriesField;
            }
            set {
                this.loadingCategoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string timetableId {
            get {
                return this.timetableIdField;
            }
            set {
                this.timetableIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.thalesgroup.com/rtti/XmlRefData/v4")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.thalesgroup.com/rtti/XmlRefData/v4", IsNullable=false)]
    public partial class LocationRef {
        
        private string tplField;
        
        private string crsField;
        
        private string tocField;
        
        private string locnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tpl {
            get {
                return this.tplField;
            }
            set {
                this.tplField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string toc {
            get {
                return this.tocField;
            }
            set {
                this.tocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string locname {
            get {
                return this.locnameField;
            }
            set {
                this.locnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.thalesgroup.com/rtti/XmlRefData/v4")]
    public partial class CategoryData {
        
        private string typicalDescriptionField;
        
        private string expectedDescriptionField;
        
        private string definitionField;
        
        private string colourField;
        
        private string imageField;
        
        private string codeField;
        
        private string nameField;
        
        private string tocField;
        
        /// <remarks/>
        public string typicalDescription {
            get {
                return this.typicalDescriptionField;
            }
            set {
                this.typicalDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string expectedDescription {
            get {
                return this.expectedDescriptionField;
            }
            set {
                this.expectedDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string definition {
            get {
                return this.definitionField;
            }
            set {
                this.definitionField = value;
            }
        }
        
        /// <remarks/>
        public string colour {
            get {
                return this.colourField;
            }
            set {
                this.colourField = value;
            }
        }
        
        /// <remarks/>
        public string image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string toc {
            get {
                return this.tocField;
            }
            set {
                this.tocField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.thalesgroup.com/rtti/XmlRefData/v4")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.thalesgroup.com/rtti/XmlRefData/v4", IsNullable=false)]
    public partial class Reason {
        
        private int codeField;
        
        private string reasontextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reasontext {
            get {
                return this.reasontextField;
            }
            set {
                this.reasontextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.thalesgroup.com/rtti/XmlRefData/v4")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.thalesgroup.com/rtti/XmlRefData/v4", IsNullable=false)]
    public partial class TocRef {
        
        private string tocField;
        
        private string tocnameField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string toc {
            get {
                return this.tocField;
            }
            set {
                this.tocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tocname {
            get {
                return this.tocnameField;
            }
            set {
                this.tocnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.thalesgroup.com/rtti/XmlRefData/v4")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.thalesgroup.com/rtti/XmlRefData/v4", IsNullable=false)]
    public partial class Via {
        
        private string atField;
        
        private string destField;
        
        private string loc1Field;
        
        private string loc2Field;
        
        private string viatextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string at {
            get {
                return this.atField;
            }
            set {
                this.atField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dest {
            get {
                return this.destField;
            }
            set {
                this.destField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string loc1 {
            get {
                return this.loc1Field;
            }
            set {
                this.loc1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string loc2 {
            get {
                return this.loc2Field;
            }
            set {
                this.loc2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string viatext {
            get {
                return this.viatextField;
            }
            set {
                this.viatextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.thalesgroup.com/rtti/XmlRefData/v4")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.thalesgroup.com/rtti/XmlRefData/v4", IsNullable=false)]
    public partial class CISSource {
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
}
